version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: barber-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yourpass}
      POSTGRES_DB: ${POSTGRES_DB:-barber_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barber-network

networks:
  barber-network:
    driver: bridge

volumes:
  postgres_data:
